# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run Selenium Cucumber Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        distribution: 'temurin'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
      
    - name: Setup Gradlew
      run: chmod +x gradlew  
      
    - name: Execute Test
      run: ./gradlew cucumber

    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: Cucumber Report
        path: reports


  deploy-test-result:
    runs-on: ubuntu-latest
    needs: selenium-test

    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: test-reports
        PUBLISH_DIR: reports
